// SPDX-License-Identifier: GPL-3.0-or-later
// Compact, versioned ABI generated by tools/native_provider.py. ARM32 and ARM64.
#pragma once
#include <cstddef>
#include <cstdint>
namespace clarity {
struct NativeKey {
  char name[32];
  uint64_t size;
  uint8_t value[64];
};
struct NativeABI {
  uint64_t magic, version;
  int (*unwrap)(const void *context, const void *cipher, size_t size, void *iv,
                void *out, int format);
#if UINTPTR_MAX == UINT32_MAX
  uint32_t reserved; // Keep the on-disk ABI offsets identical on both ABIs.
#endif
  uint8_t context[288];
  uint8_t decode[16][256];
  uint64_t keyCount;
  NativeKey keys[31];
};
static_assert(offsetof(NativeABI, context) == 24);
static_assert(offsetof(NativeABI, keyCount) == 4408);
static_assert(offsetof(NativeABI, keys) == 4416);
static_assert(sizeof(NativeABI) == 7640);
} // namespace clarity
